version: 1.0
configuration:
  showDiagnosticInformation: false
  defaultCommand: commands
  codeEditor: C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\Code.exe
  repository: https://github.com/PowerCommands/PowerCommands2022
  backupPath: ..\..\..\..\Core\PainKiller.PowerCommands.Core\        
  dockerDesktop:
    path: C:\Program Files\Docker\Docker
    startupTime: 15
  cdxgen:
    sdxGenServerVolumeMount: E:\Temp\Cdxgen_server
    imageUrl: ghcr.io/cyclonedx/cdxgen:latest 
    hostPort: "9090"
    containerPort: "9090"
    hostMount: /tmp
    containerMount: /tmp
    serverHost: "0.0.0.0"    
    sbomApiUrl: http://127.0.0.1:9090/sbom
    resolveLicenses: true
  dependencyTracker:
    urlToDockerComposeFile: https://dependencytrack.org/docker-compose.yml    
    adminUrl: http://localhost:8080
    apiUrl: http://localhost:8081
    sbomApiUrl: /api/v1/bom
    startupTime: 5
    apiServerImage: dependencytrack/apiserver
    apiServerContainer: dtrack-apiserver
    apiPorts: 8081:8080
    frontendImage: dependencytrack/frontend    
    frontendContainer: dtrack-frontend
    frontendPorts: 8080:8080
  epss:
    apiUrl: https://api.first.org/data/v1/epss?cve=
  startupToolbar:
    hideToolbarOption: OnCommandHighlighted
    toolbarItems:
    - label: "[Type ->]"
      color: "Cyan"
    - label: "demo"
      color: "DarkGreen"
  metadata:
    name: SecTools
    description: Description of my project
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 13b9944b55efe60362720a679f17a22c
    name: Serialog
  components:  
  - component: SecToolsCommands.dll
    checksum: a2df61ea89e4f9ec265d921bfad87193
    name: SecTools
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 4f04313db8e67b2bc4b059c478a900af
    name: PainKiller Core
  bookmark:
    bookmarks:
    - name: Program
      path: C:\Program Files
      index: 0
  secret:
    secrets:
    - name: DT_PowerCommand
      options:
        target: User
  environment:
    variables:
    - name: OS
      environmentVariableTarget: Machine